# Generated by Django 5.2.4 on 2025-07-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_predefined_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Santiago', max_length=100),
        ),
    ]
